### ISSUE TITLE
本人確認

### ISSUE THREAD

**Issue by yuasabe** [jphacks/B_2011#1]
**Is your feature request related to a problem? Please describe.**
- 試験開始前に本人確認を簡単にできる仕組みを用意したい。

**Describe the solution you'd like**
- 本人ID（学生書、免許証、パスポート ）をカメラに表示し、登録済みのIDの顔画像と比較する。
- 試験中に定期的に受験者の画像を取得し、登録済みIDの顔画像と比較する。

**Describe alternatives you've considered**

**Additional context**

**Comment by bentaro** [comment]
・https://github.com/ageitgey/face_recognition
などを用いて、受験者の顔画像と現在のカメラ前にいる人物画像との類似度を測る
・1秒に1回程度の照合で十分?
・https://github.com/vardanagarwal/Proctoring-AI
との兼ね合いも考慮
