### ISSUE TITLE
データ送信先のサーバー+試験管理者のUI

### ISSUE THREAD

**Issue by bentaro** [jphacks/B_2011#13]
・それぞれのクライアントモジュールorプールからJSON形式でデータを受け取ることを想定
・データの形式は
{
  "exam_id": "123abc",
  "tester_id": "789xyz",
  "tester_name": "toefl"
  "examinee_id" :  "456efg",
  "messages": [{"module_name" : "window", "alert" : "True", "description" : "クリップボードへのコピーを確認しました。 ”},
{"module_name" : "image_validation", "alert" : "False", "description" : "受験者は着席しています。”}]
}

のようなJSONを数秒ごとにクライアントからもらうことを想定
・とりあえずDjangoで書いてみる
・その他要りそうな要素があれば書いてください〜

**Comment by fiord** [comment]
データ形式はよさそうです。保存時には時刻情報を加える必要があります、くらい？

**Comment by bentaro** [comment]
content, description内のクオートに注意

**Comment by bentaro** [comment]
とりあえず下記のような形式でAPIを叩けば返ってくる感じにしました。
curl 'localhost:8000/api/message/list?examinee_id=69bc4034-97fd-47e3-b0b7-ec16e56c1843'

curl -X POST -H "Content-Type: application/json" -d '[{"examinee_id" : "69bc4034-97fd-47e3-b0b7-ec16e56c1843" , "exam_id" : "961ab556-f2c6-47ef-bfda-efdf9193cc7d","module_name" : "video", "alert" : "False" ,"description" : "受験者は着席しています。","content":"うぇい"}]' localhost:8000/api/message/post/

**Comment by bentaro** [comment]
demo.ben.hongo.wide.ad.jp:8000に開発用サーバー設置
curl 'demo.ben.hongo.wide.ad.jp:8000/api/message/list?examinee_id=69bc4034-97fd-47e3-b0b7-ec16e56c1843'
