### ISSUE TITLE
USB接続のカメラが正常に認識されない

### ISSUE THREAD

**Issue by yuasabe** [jphacks/B_2011#42]
PC内蔵のカメラは認識されるが、外部接続されたUSBカメラが正常に認識されない。

**Comment by fiord** [comment]
これはカメラのidが異なるため？idからデバイスを取得、選択させる画面を作るとよさそうか？

**Comment by yuasabe** [comment]
遅くなってごめん！
そうだと思う。USB外付けのカメラとかだとIDを正しく拾ってこれてなさそうで、一応カメラの一覧を画面上部のselectで表示させて、そこから選べるようにした。
