### ISSUE TITLE
カメラに写っている1人が本人か検出できるか(画像の類似度を取るなど)

### ISSUE THREAD

**Issue by bentaro** [jphacks/B_2011#5]
カメラに映る人物の照合を行う

・https://github.com/ageitgey/face_recognition
などを用いて、受験者の顔画像と現在のカメラ前にいる人物画像との類似度を測る
・1秒に1回程度の照合で十分?
・https://github.com/vardanagarwal/Proctoring-AI
との兼ね合いも考慮

**Comment by bentaro** [comment]
重複を確認

**Comment by fiord** [comment]
duplicated with #1
