### ISSUE TITLE
音声録音の画面の作成

### ISSUE THREAD

**Issue by yuasabe** [jphacks/B_2011#54]
音声録音の画面をつくる。
写真IDの撮影画面→音声録音の画面→試験受験準備の画面→試験受験画面、の流れでいいかな。

・任意の文字列を表示
・録音ボタンを押すと録音が開始され、停止ボタンを押すと録音が停止
・録音された音声はwav形式でtestModule/wav配下にとりあえず保存
（・録音したあとの再生機能があると良い）

**Comment by kanaya516** [comment]
@yuasabe 
「あ」「い」「う」「え」「お」をそれぞれ5秒ずつ録音したものを、それぞれ0_a.wav 0_i.wav 0_u.wav 0_e.wav 0_o.wavというファイル名にしてclient/testModule/voice/wavに入れてほしいです！

**Comment by yuasabe** [comment]
@Koichiro-Kanaya 
了解しました！！あと素朴な疑問なのですが、

「あ」の録音の場合、「あーーーー」のように5秒間発声し続ける感じですか？
それとも、「あっ、あっ、あっ」って繰り返す感じですか？
それとも、一回「あー。」っていえばいい感じですか？

**Comment by kanaya516** [comment]
@yuasabe 
一回だけ「あーーーーーーーー」って5秒間言い続けてもらいたいです！

**Comment by yuasabe** [comment]
はーい！理解理解！

**Comment by kanaya516** [comment]
client/testModule/python_code/voice/wav
に作ってください！間違えたんご〜
