### ISSUE TITLE
音声/人の入れ替わり検出で用いるrequirements.txtが消失している

### ISSUE THREAD

**Issue by fiord** [jphacks/B_2011#74]
https://github.com/jphacks/B_2011/blob/feature/fullscreen-check/client/testModule/requirements.txt
で復旧出来そう？

**Comment by kanaya516** [comment]
音声の分はあとでpushしておきます。
場所はclient/testModule/python_code/voiceとかでいいですか？

**Comment by fiord** [comment]
solved
